### ISSUE TITLE
Progress bar no longer launches [BUG]

### ISSUE THREAD

**Issue by Jumitti** [Wirg/stqdm#91]
**Describe the bug**

I'm using the progress bar to track a process in my script.
I can't set the bar like "for _ in stqdm(range(x)):" because I have several loops to control process and I only want one bar.

after several uses or when I do large calculations, the bar is no longer usable and the script no longer works. There is no error displayed and the bar is no longer displayed. However the st.spinner launches well before.

**To Reproduce**

```python
import streamlit as st
from stqdm import stqdm

def exemple_run(test1, test2):
    total_iterations = len(test1) + len(test2)
    with stqdm(total=total_iterations, desc='Calculating...', mininterval=0.1) as pbar:
         for _ in test1:
            pbar.update(1)
         for _ in test2:
            pbar.update(1)

if st.button("Exemple"):
   with st.spinner("Processing..."):
      exemple_run(test1, test2)
```

**Desktop (please complete the following information):**

 - Browser: this is a Streamlit Cloud
 - Version of streamlit: latest
 - Version of stqdm: latest
 - Version of tqdm: latest

**Comment by Wirg** [comment]
Hi @Jumitti ,

I tried to reproduce your example here : https://stqdm-bugs-with-concatenated-iterator.streamlit.app/
With the following code https://github.com/Wirg/stqdm/blob/0c2e476abdd1aa1ac5f0fb1b4b58eb96d1ddd551/examples/bugs_with_concatenated_iterator.py . I had to infer what test1 / test2 could be.

Does it fit what you're doing ?

Can you clarify what you're doing to enter the blocking situation ?
I really had to mash the buttons especially both "Exemple" and the "STOP" (from streamlit interface) to run into a blocking situation. Then it solves itself if I just reload the page.
It does not seem to be what you are running into tho.
Does it need to be longer ?

**Comment by Jumitti** [comment]
Hello @Wirg 

Thanks to answer :)

Your code is very similar to mine, at least in the process.

I think after reflection and a lot of testing that it is due to the processing speed of Streamlit Cloud or the 1GB RAM.

I have this problem in 3 cases.
When I do too many pbar.update(1)
When my function takes too long
When I modify a widget which is necessary to launch the function.

In the first 2 cases I think it's the 1GB of RAM that breaks everything. And for the 3rd case I think it's the fact that Streamlit restarts the whole script as soon as you make a modification with a widget.
I tried STOP during the execution of the function but it still creates the bug. After refreshing the application page, all functions where stqdm is used no longer work until I completely reboot the application.
I think that's really the way Streamlit Cloud is made. Because when I do it locally it works fine. 

For information, I do more than 75,000,000 calculations with one function. I ask a lot of streamlit :)
And it's probably not an .update problem. I decreased the number of .updates I do and I also had the problem.

**Comment by Wirg** [comment]
Hi @Jumitti 

You're probably asking a bit too much from their 1GB of RAM.
On the stqdm-side you might be able to reduce the load by relying on [tqdm parameters](https://github.com/tqdm/tqdm#parameters). They've done a lot of work to handle this kind of things.

For example, you could set mininterval to 0.5s so that there are around 5x less updates to do.

There could be some locking issue with stqdm / streamlit in some cases.
I still need to investigate but it seems that :
- on windows there is the locking issue reported here
- in some case with numerous forced stops or disconnection, there is a sort of race condition that could not completely stop the process. I need to take the time to properly investigate this but it seems to be pretty niche.

**Comment by Jumitti** [comment]
Hi @Wirg 

Thanks you again, and yes i think your are right 😅

Yes i try to set an higher mininterval. But bug append also. It's really a problem between how python works and how streamlit cloud works i think.

On my PC in localhost there is no problem. So good luck to find how to solve it with Streamlit Cloud 😅 If you need any help, let me know 😊
